name: "Build & Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # Replaced self-hosted runners
        arch: [X64, ARM64] # Separate architecture matrix
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - uses: cachix/cachix-action@v15
      with:
        name: nixpkgs-python
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --keep-going --accept-flake-config --show-trace
